name: Deploy to GitHub Pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      
      -  name: Checkout Code
         uses: actions/checkout@v3

      
      -  name: Set up Node.js
         uses: actions/setup-node@v3
         with:
            node-version: 18
            cache: 'npm'

            
      -  name: Install Dependencies
         run: npm ci  # Ensures clean and consistent dependency installation

            
      -  name: Build React App (Vite)
         run: npm run build && mv dist mega-city-cab-frontend  # Rename output folder

            
      -   name: Log into Docker Hub
          run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            
      -    name: Docker Build
           run: |
             docker build -t ${{ secrets.DOCKER_USERNAME }}/mega-city-cab-frontend .

            
      -  name: Publish Docker Image
         run: |
            docker push ${{ secrets.DOCKER_USERNAME }}/mega-city-cab-frontend:latest